[package]
name = "raft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actum = { git = "https://github.com/andreastedile/actum.git" }
futures = "0.3.30"
tracing = { version = "0.1.40", default-features = false }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "time"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }